# Generated by Django 4.1 on 2023-12-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name_plural': 'destinations'},
        ),
    ]
