# Generated by Django 4.1 on 2023-12-07 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_destination_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreLocations',
            fields=[
                ('location_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('city', models.TextField(blank=True, null=True)),
                ('county', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('country_code', models.TextField(blank=True, null=True)),
                ('address_type', models.TextField(blank=True, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('lat', models.TextField(blank=True, null=True)),
                ('lon', models.TextField(blank=True, null=True)),
                ('radius_km', models.BigIntegerField(blank=True, null=True)),
                ('box_bottom_left_lat', models.TextField(blank=True, null=True)),
                ('box_bottom_left_lon', models.TextField(blank=True, null=True)),
                ('box_top_right_lat', models.TextField(blank=True, null=True)),
                ('box_top_right_lon', models.TextField(blank=True, null=True)),
                ('geojson', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_locations',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.CreateModel(
            name='CoreLocationScores',
            fields=[
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='destinations.corelocations')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('dimension', models.CharField(max_length=255)),
                ('subcategory', models.CharField(max_length=255)),
                ('scores', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_location_scores',
                'managed': False,
            },
        ),
    ]
