# Generated by Django 4.1 on 2024-01-05 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_corelocations_delete_destination_corelocationscores'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreCategories',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreDimensions',
            fields=[
                ('dimension_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dimension', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_dimensions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreScores',
            fields=[
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='destinations.corelocations')),
                ('score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_scores',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CoreLocationScores',
        ),
    ]
