CREATE TABLE IF NOT EXISTS raw_accommodation_costs (
    location_id INTEGER NOT NULL,
    kayak_city VARCHAR(100) NOT NULL,
    kayak_country VARCHAR(50) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    n_hotels INTEGER,
    avg_price FLOAT,
    comp_avg FLOAT,
    comp_median FLOAT,
    bin_height_1 INTEGER,
    bin_height_2 INTEGER,
    bin_height_3 INTEGER,
    bin_height_4 INTEGER,
    bin_height_5 INTEGER,
    bin_height_6 INTEGER,
    bin_height_7 INTEGER,
    bin_height_8 INTEGER,
    bin_height_9 INTEGER,
    bin_height_10 INTEGER,
    bin_height_11 INTEGER,
    bin_height_12 INTEGER,
    bin_height_13 INTEGER,
    bin_height_14 INTEGER,
    bin_height_15 INTEGER,
    bin_height_16 INTEGER,
    bin_height_17 INTEGER,
    bin_height_18 INTEGER,
    bin_height_19 INTEGER,
    bin_height_20 INTEGER,
    bin_height_21 INTEGER,
    bin_height_22 INTEGER,
    bin_height_23 INTEGER,
    bin_height_24 INTEGER,
    bin_height_25 INTEGER,
    bin_height_26 INTEGER,
    bin_height_27 INTEGER,
    bin_height_28 INTEGER,
    bin_height_29 INTEGER,
    bin_height_30 INTEGER,
    bin_bound_1 INTEGER,
    bin_bound_2 INTEGER,
    bin_bound_3 INTEGER,
    bin_bound_4 INTEGER,
    bin_bound_5 INTEGER,
    bin_bound_6 INTEGER,
    bin_bound_7 INTEGER,
    bin_bound_8 INTEGER,
    bin_bound_9 INTEGER,
    bin_bound_10 INTEGER,
    bin_bound_11 INTEGER,
    bin_bound_12 INTEGER,
    bin_bound_13 INTEGER,
    bin_bound_14 INTEGER,
    bin_bound_15 INTEGER,
    bin_bound_16 INTEGER,
    bin_bound_17 INTEGER,
    bin_bound_18 INTEGER,
    bin_bound_19 INTEGER,
    bin_bound_20 INTEGER,
    bin_bound_21 INTEGER,
    bin_bound_22 INTEGER,
    bin_bound_23 INTEGER,
    bin_bound_24 INTEGER,
    bin_bound_25 INTEGER,
    bin_bound_26 INTEGER,
    bin_bound_27 INTEGER,
    bin_bound_28 INTEGER,
    bin_bound_29 INTEGER,
    bin_bound_30 INTEGER,
    bin_bound_31 INTEGER, 
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc-01')
    );

ALTER TABLE raw_accommodation_costs ADD PRIMARY KEY (location_id, start_date);
ALTER TABLE raw_accommodation_costs ADD FOREIGN KEY (location_id) REFERENCES core_locations (location_id);
        
COMMENT ON TABLE raw_accommodation_costs IS 'Table stores accomodation data for location, start_date, end_date triplets'